CREATE DATABASE JUEGO_MEMORIA --CREMOS LA BASE DE DATOS
USE JUEGO_MEMORIA;

CREATE TABLE INFORMACION_JUGADOR(--CREMOS LOS CAMPOS CORRESPONDIENTES
ID_JUGADOR		INT IDENTITY(1,1) PRIMARY KEY,
ALIAS			VARCHAR(11) NOT NULL,
MOVIMIENTOS		INT NOT NULL,
ERRORES			INT NOT NULL,
ACIERTOS		INT NOT NULL,
TIEMPO			TIME(0) NOT NULL);-- ALMACENA DATOS EN EL FORMATO 'HH:MM:SS'

SELECT *FROM INFORMACION_JUGADOR;--CONSULTA DE PRUEBA
--PROCESO PARA MOSTRAR LA INFORMACION DE LAS MEJORES ESTADISTICAS DE JUEGO MENOS CANTIDAD DE ERRORES Y MAYOR ACIERTOS
USE JUEGO_MEMORIA;  
GO  
CREATE PROCEDURE RECORDS   --NOMBRAMSO LA FUNCION O EL PROCESO
AS   
SELECT	 ALIAS,MOVIMIENTOS,ERRORES,ACIERTOS,TIEMPO 
FROM	 INFORMACION_JUGADOR
WHERE MOVIMIENTOS>9 ORDER BY ACIERTOS desc, ERRORES Asc;

GO  
EXECUTE RECORDS-- EJECUTAMOS DESDE EL PROGRMA PARA QUE AL INICIO PODAMOS TENER UNA MEJOR VISTA SOBRE LAS ESTADISTICAS

DROP PROCEDURE [RECORDS];
